-- =============================================================================
-- Superseded. Use `pnpm seed` instead.
--
-- This file inserted `profiles` rows directly, but profiles.id references
-- auth.users, and auth.users cannot be populated with plain SQL — Supabase Auth
-- owns password hashing, identity records and confirmation state. Every insert
-- here failed on a foreign key violation.
--
-- The replacement is packages/backend/src/scripts/seedDemo.ts, which creates
-- auth users through the Admin API, then the domain rows, then uploads and
-- processes real photos through the same code path the app uses.
--
--   pnpm seed              # idempotent
--   pnpm seed:demo:reset   # wipe first
--
-- See docs/environment-setup.md.
-- =============================================================================
